---
language: node_js
node_js:
  - "6"

branches:
  only:
    - "master"

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache

before_install:
  - npm install -g phantomjs-prebuilt
  - yarn --version
  - phantomjs --version

install:
  - yarn install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - npm run $NPM_COMMAND

env:
  matrix:
  - NPM_COMMAND=test
  - CXX=g++-4.8 NPM_COMMAND=electron-test
