# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

clone_depth: 1

platform:
  - x64

# cache:
#   - node_modules -> package.json
#   - '%APPDATA%\npm-cache'

branches:
  only:
    - master
    - production
    - dev

install:
  - ps: Install-Product node 8 x64
  - npm version
  - npm install --no-color --no-progress

build_script:
  - npm run-script ember-electron

test_script:
  - npm build
  - npm test
  - npm run-script electron-test

artifacts:
  - path: electron-out\make\squirrel.windows\ia32
    name: HospitalRunElectronWin32

  - path: electron-out\make\squirrel.windows\x64
    name: HospitalRunElectronWin64

# deploy:
#  provider: S3
#  access_key_id: $(ARTIFACTS_ACCESS)
#  secret_access_key: $(ARTIFACTS_SECRET)
#  bucket: $(ARTIFACTS_BUCKET)
#  region: eu-west-1
#  unzip: true|false (disabled by default)
#  set_public: true|false (disabled by default)
#  folder:
#  artifact: HospitalRunElectron32, HospitalRunElectron64

version: "{build}"
